providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]
nixLibs = ["openssl"]

[phases.install]
cmds = [
  "npm install -g pnpm@9.12.0",
  "pnpm install --frozen-lockfile=false",
]

[phases.build]
cmds = [
  "pnpm db:generate",
  "pnpm --filter @vp/web build",
]

[start]
cmd = "pnpm db:push --accept-data-loss && pnpm --filter @vp/web start"
